version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: medical-backend-mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Medical@951753
      MYSQL_USER: medical
      MYSQL_PASSWORD: Medical@951753
      MYSQL_DATABASE: medical-prisma
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: medical-backend-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --requirepass Medical@951753
    volumes:
      - ./redis/data:/data

volumes:
  mysql_data:
  redis_data:
